import { FileUser, GraduationCap, UserRound, PenLine, Mail } from 'lucide-react';
import { SiteHeader, SiteFooter } from '@/components/site-chrome';
import Markdown from '@/components/markdown';
import SocialLinks from '@/components/social-links';
import { getProfile } from '@/lib/profile';

export const metadata = { title: '个人简介', description: '个人介绍、教育背景、简历与联系方式。' };
function Placeholder({ title, text, items, owner }: { title: string; text: string; items: string[]; owner: boolean }) { return <div className="profile-placeholder"><h3>{title}</h3><p>{text}</p><div className="topic-chips">{items.map(item => <span key={item}>{item}</span>)}</div>{owner && <a className="text-button" href="/studio/profile"><PenLine size={15} />填写个人资料</a>}</div>; }
export default async function About() {
 const owner = false;
 let profile; try { profile = await getProfile(); } catch (error) { console.error(error); return <div className="site-shell"><SiteHeader active="about" /><main className="studio-main"><h1>个人资料暂时无法加载</h1><p className="notice">请稍后刷新页面。</p><a className="button secondary" href="/about">重新加载</a></main><SiteFooter /></div>; }
 return <div className="site-shell"><SiteHeader active="about" /><main><header className="about-header"><div className="breadcrumbs"><a href="/">首页</a><span>/</span><span>个人简介</span></div><h1>你好，我是{profile.name}。</h1><p>{profile.tagline}</p></header><div className="about-layout"><nav className="about-nav" aria-label="个人资料目录"><a href="#introduction">基本信息</a><a href="#resume">个人简历</a><a href="#contact">联系方式</a>{owner && <a className="button secondary" href="/studio/profile"><PenLine size={15} />编辑个人资料</a>}</nav><div><section className="profile-section" id="introduction"><div className="profile-section-title"><UserRound size={24} /><h2>关于我</h2></div><div className="profile-summary"><img className="profile-avatar" src="/hui-portrait-v2.jpg" alt={`${profile.name}的个人照片`} width="96" height="96" /><div><h3>{profile.name}</h3><p>{profile.identity || '探索、实践，也记录生活。'}</p></div></div>{profile.bio ? <Markdown content={profile.bio} /> : <Placeholder title="个人介绍待补充" text="研究兴趣与个人经历将在这里展示。" items={['个人介绍', '研究兴趣', '个人特长']} owner={owner} />}<div className="about-data"><div className="skill-tags">{profile.skills.split(/[,，\n]/).map(s => s.trim()).filter(Boolean).map((skill, i) => <span key={`${skill}-${i}`}>{skill}</span>)}</div></div><h3><GraduationCap size={20} style={{display:'inline', marginRight:9, verticalAlign:'middle'}} />教育背景</h3>{profile.education ? <Markdown content={profile.education} /> : <p className="profile-saved">教育经历待补充。</p>}</section><section className="profile-section" id="resume"><div className="profile-section-title"><FileUser size={24} /><h2>个人简历</h2></div>{profile.resume ? <Markdown content={profile.resume} /> : <Placeholder title="个人简历待补充" text="简历内容整理中。" items={['个人经历', '专业技能', '成果与荣誉']} owner={owner} />}</section><section className="profile-section" id="contact"><div className="profile-section-title"><Mail size={24} /><h2>联系方式</h2></div>{profile.email ? <a className="contact-email" href={`mailto:${profile.email}`}>{profile.email}</a> : <p className="contact-empty">联系邮箱待补充。</p>}<SocialLinks profile={profile} />{owner && <a className="text-button" href="/studio/profile">设置邮箱与社交链接</a>}</section></div></div></main><SiteFooter /></div>;
}
